def observatory():
    obser = input ("Welcome to the observatory. Here you can... well... observe. Would you like to? Y/N").strip().lower()
    if obser == ("y"):
        input("Alright take a look!")
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        print()
        input("You see a neverending, colorful land, full of nature.")
        input("You stand there")
        input("Overwhelmed by the vast beauty")
        input("Amazed that in this world")
        input("Full of insanity and chaos")
        input("That you were able to find such beauty")
        input("The landscape stretches back as far as your eye can see")
        input("You're upset that this is a text based RPG, and you can't actually see anything")
        input("Looks like it's time to leave!")
    elif obser == ("n"):
        input("Oh well, Goodbye then!")
        #load the road wherever this is XD
    else:
        print("YES OR NO QUESTION. Jeez, some people.")
        observatory()        
observatory()
